### ISSUE TITLE
Need to apt-get install make for local conda build

### ISSUE THREAD

**Issue by RobertBaruch** [hdl/conda-eda#10]
In README.md, the instructions need to be updated to:

```
sudo apt-get install coreutils make
```

as a fresh docker image of ubuntu has no make.

**Comment by RobertBaruch** [comment]
(Note that sudo is not used for a docker image, as apparently you get dumped into root anyways)

**Comment by RobertBaruch** [comment]
Possibly this should be a conda dependency? I've also noted that formal/symbiyosys required binutils and cmake to be installed as well.

**Comment by mithro** [comment]
These dependencies should be part of the `meta.yaml`.
