### ISSUE TITLE
The "icestorm" package does not contain the "iceprog" executable (Linux)

### ISSUE THREAD

**Issue by tcal-x** [hdl/conda-eda#156]
A user using the conda install ran into an error 
```
FileNotFoundError: [Errno 2] No such file or directory: 'iceprog': 'iceprog'
```
and I confirmed that `iceprog` is not in the `icestorm` package from https://anaconda.org/litex-hub/icestorm.

It is not in the `nextpnr-ice40` package either. 

Is there another package I need to install to get `iceprog`?

**Comment by PiotrZierhoffer** [comment]
I think it's just https://anaconda.org/litex-hub/iceprog

**Comment by tcal-x** [comment]
Thanks, I didn't see that!
