### ISSUE TITLE
`build-packages` failed to publish packages

### ISSUE THREAD

**Issue by proppy** [hdl/conda-eda#186]
Manually tried to reschedule it:
https://github.com/hdl/conda-eda/actions/runs/1895830225/attempts/2

But logging this here, so we can investigate what was going wrong:
https://github.com/hdl/conda-eda/actions/runs/1895830225/attempts/1

**Comment by proppy** [comment]
- [nextpnr-xilinx-linux](https://github.com/hdl/conda-eda/runs/5326526466?check_suite_focus=true#logs) failed with a timeout

**Comment by ajelinski** [comment]
Yosys-uhdm and plugins problems have been fixed already:
* https://github.com/hdl/conda-eda/commit/a976b2691dac504afa969a12a475f20c1af68122
* https://github.com/hdl/conda-eda/commit/bd20ad0fe817a38c9353e1eaae2483d212cbf4b1
