### ISSUE TITLE
add SUPREM package

### ISSUE THREAD

**Issue by simbilod** [hdl/conda-eda#239]
Hello, how could we get a conda build for SUPREM?

https://github.com/cogenda/Suprem4

Thank you!

**Comment by mithro** [comment]
Sadly SUPREM isn't open source and thus can't be included. See the text below;

> (C) Copyright (1994) The Board of Trustees of the Leland Stanford Junior
> University. **Except for commercial resale, lease, license or other commercial
> transactions**, permission is hereby given to use, copy, modify, and
> distribute this software. STANFORD MAKES NO REPRESENTATIONS OR WARRANTIES
> OF ANY KIND CONCERNING THIS SOFTWARE.

A lot of the source files also have a header like this;
```
/*************************************************************************
 * *
 *     Copyright c 1984 The board of trustees of the Leland Stanford *
 *                      Junior University. All rights reserved. *
 *     This subroutine may not be used outside of the SUPREM4 computer *
 *     program without the prior written consent of Stanford University. *
 * *
 *     Copyright c 1991 The board of regents of the University of *
 *                      Florida.  All rights reserved. *
 *     This subroutine may not be used outside of the SUPREM4 computer *
 *     program without the prior written consent of the University of *
 *     Florida. *
 * *
 * *
 *************************************************************************/
````
