### ISSUE TITLE
Conda packages are not getting published

### ISSUE THREAD

**Issue by saicharan0112** [hdl/conda-eda#255]
Packages are not getting published event though the tools are getting updated. By when can we expect the latest packages online? 

FYI - @mithro @msaligane @proppy

**Comment by proppy** [comment]
Looks like the actions are currently failing, preventing the package to be published:
https://github.com/hdl/conda-eda/actions/runs/3432621227

/cc @PiotrZierhoffer @ajelinski

**Comment by proppy** [comment]
```
  Error:  ('Storage requirements exceeded (107374182400 bytes). Payment is required to add a file. Please go to https://anaconda.org/binstar.settings/billing to update your plan', 402)
```

Looks like we exceeded the anaconda quota. Time to move the channel to GCS? /cc @mithro

**Comment by PiotrZierhoffer** [comment]
For now I'll try to clean up unused versions of packages, this should buy us some time

**Comment by saicharan0112** [comment]
Thanks @PiotrZierhoffer @proppy Looks like the latest packages are available now.
