### ISSUE TITLE
upgrade to python 3.8

### ISSUE THREAD

**Issue by proppy** [hdl/conda-eda#260]
python 3.7 is EOL'ed next year, and colab has recently updated to 3.8:
https://twitter.com/GoogleColab/status/1598059818769870849

The colab fallback Python 3.7 runtime will only available until mid-December, see https://medium.com/google-colab/colab-updated-to-python-3-8-4922f9970a72

So until then we should make sure to have 3.8 versions of the packages available.

**Comment by mithro** [comment]
We should make sure to have packages for Python 3.9, 3.10 and 3.11

**Comment by erendn** [comment]
As I mentioned in https://github.com/KLayout/klayout/issues/1263, installing klayout gives python version conflict with other tools using python 3.8.

**Comment by proppy** [comment]
Duplicate with #72.
