### ISSUE TITLE
Magic package is not getting uploaded even after release of latest revision

### ISSUE THREAD

**Issue by saicharan0112** [hdl/conda-eda#322]
I see that conda package version (8.3.389) and the release tag from Magic Github repo (8.3.392) are not in sync. Is there a reason behind it?

cc: @proppy, @msaligane

**Comment by proppy** [comment]
Looks like the osx build is failing:
https://github.com/hdl/conda-eda/actions/runs/4769548675/jobs/8480013022

**Comment by proppy** [comment]
The following patch https://github.com/hdl/conda-eda/blob/master/misc/magic/rename-region-to-netregion.patch doesn't seems to be needed anymore, since it has been applied upstream:
https://github.com/RTimothyEdwards/magic/commit/1e7da74672cfa6bc7bc7b213812acfe4e18fef8f
