### ISSUE TITLE
openroad binary library issue, missing library

### ISSUE THREAD

**Issue by saicharan0112** [hdl/conda-eda#357]
I installed openroad conda package (openroad-2.0_10145_g0de6f5131) but looks like the binary is missing some libraries. 
I am running it on ubuntu:22 with conda 23.9.0. 

/usr/bin/miniconda3/bin/openroad: error while loading shared libraries: libfmt.so.8: cannot open shared object file: No such file or directory
Command exited with non-zero status 127

**Comment by saicharan0112** [comment]
Yesterday I managed to install it. Not sure what went wrong while installing the conda packages. I will debug more and write it down here just in case if someone might come across this

**Comment by chetanyagoyal** [comment]
> Yesterday I managed to install it. Not sure what went wrong while installing the conda packages. I will debug more and write it down here just in case if someone might come across this

Fixed the reproduced error by running - 
`sudo apt install libfmt-dev`
