### ISSUE TITLE
Symbiyosys not showing up in conda packages

### ISSUE THREAD

**Issue by RobertBaruch** [hdl/conda-eda#4]
https://anaconda.org/litex-hub/repo does not show symbiyosys.

**Comment by mithro** [comment]
Currently you caught us mid-transition to splitting apart https://github.com/litex-hub/litex-conda-packages repository - see https://github.com/litex-hub/litex-conda-packages/issues/114

**Comment by mithro** [comment]
Currently only packages from https://github.com/litex-hub/litex-conda-packages are uploaded to https://anaconda.org/litex-hub/repo

**Comment by RobertBaruch** [comment]
That does explain a few things. Including the comments in the manual build section mentioning compilation of gcc and binutils!
