### ISSUE TITLE
Add ngspice package

### ISSUE THREAD

**Issue by mithro** [hdl/conda-eda#49]
nspice is needed for analog simulation of the spice models in the skywater-pdk (and for OpenRAM characterization).

**Comment by mithro** [comment]
Make sure that ngspice is compiled with parallel support too.

**Comment by mithro** [comment]
> A general preprocessor flag USE_OMP is set by ./configure, if OpenMP is available and the applying option --enable-openmp.

**Comment by mithro** [comment]
http://ngspice.sourceforge.net/docs/ngspice-30-manual.pdf

**Comment by proppy** [comment]
See also https://github.com/conda-forge/ngspice-feedstock
