### ISSUE TITLE
TRAVIS_OS_NAME must be set before running conda-get.sh

### ISSUE THREAD

**Issue by RobertBaruch** [hdl/conda-eda#9]
In attempting to do a pseudo-Travis build as in README.md, https://github.com/litex-hub/litex-conda-eda/blob/master/conda-get.sh#L7 requires that TRAVIS_OS_NAME be set, otherwise you'll end up running an OSX version. Which is great if you're on OSX, but not so great otherwise.

**Comment by mithro** [comment]
Opps! We should most certainly fix this to detect the OS manually if `TRAVIS_OS_NAME` isn't found.
